### ISSUE TITLE
Graphic Recording on Workshop

### ISSUE THREAD

**Issue by mapconcierge** [unvt/design-2021-05#1]
![UNVTws20210513_grareco_bymapconcierge](https://user-images.githubusercontent.com/416977/117999696-0f5ef800-b380-11eb-8fb9-31f37df9a958.jpg)

↓ 日付間違えたので修正
![image](https://user-images.githubusercontent.com/416977/118066929-86c17580-b3da-11eb-962e-092e54e51d59.png)
© mapconcierge/FuruhashiLab, CC BY 4.0

**Comment by hfu** [comment]
あっ、このグラレコを英語にして逆輸出すればインパクトありそうです！

**Comment by halgraphic** [comment]
![UNVTWS_english](https://user-images.githubusercontent.com/30142846/118204688-c4390800-b499-11eb-824b-84bc464634d6.jpg)

**Comment by hfu** [comment]
Many thanks! Reflected in https://unvt.github.io/512/.
