### ISSUE TITLE
Graphic Recording English ver

### ISSUE THREAD

**Issue by halgraphic** [unvt/design-2021-05#2]
![UNVTWS_english](https://user-images.githubusercontent.com/30142846/118204823-11b57500-b49a-11eb-9e10-b3bee8c3fa68.jpg)

**Comment by halgraphic** [comment]
[UNVTWS_english.psd.zip](https://github.com/unvt/design-2021-05/files/6475856/UNVTWS_english.psd.zip)
Psd data

**Comment by hfu** [comment]
Many thanks! Reflected in https://unvt.github.io/512/.
